# External gems
plugins:

include:
  - "/_redirects"

exclude:
  - "/vendor/"
  - "/Gemfile"
  - "/Gemfile.lock"
  - "/LICENSE"
  - "/README.md"

# Site settings
title: codelerity
subtitle:
name: codelerity
description:
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "https://www.codelerity.com"
logo:
email: info@codelerity.com

# Build settings
markdown: kramdown
permalink: pretty

# Image CDN
imagecdn:
  production: "https://images.weserv.nl?url=ssl:www.codelerity.com"
  #development: "https://images.weserv.nl?url=www.codelerity.com"

# Collections
collections:
    projects:
        output: true
        permalink: /projects/:path/


# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "projects"
        values:
            layout: "project"
            

# Google analytics
# ga_tracking_id: "UA-XXXX-1"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: codelerity
    url: https://twitter.com/codelerity
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: 
    url: 
    desc: Like us on Facebook
    share: true

  - name: GitHub
    icon: github
    username: codelerity
    url: https://github.com/codelerity
    desc: Fork us on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username:
    url:
    desc: Connect with us on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share: true

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/codelerity-splash.jpg"
    fb_image_width: 1600
    fb_image_height: 1100
    fb_image_type: "image/jpeg"

    twitter_image: "/assets/codelerity-splash.jpg"

